import NavBar from '@/components/navbar'
import './globals.css'
import { Lora } from 'next/font/google'
import Footer from '@/components/footer'

const lora = Lora({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={` relative ${lora.className}`}>
        <NavBar />
        <div>
        {children}
        </div>
        <Footer />

        </body>
    </html>
  )
}
