import NavBar from '@/components/navbar'
import './globals.css'
import { Playfair_Display } from 'next/font/google'
import Footer from '@/components/footer'

const font = Playfair_Display({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={` relative ${font.className}`}>
        <div className='flex justify-center w-full'>
        <NavBar />
        </div>
        <div>
        {children}
        </div>
        <Footer />

        </body>
    </html>
  )
}
